### ISSUE TITLE
経歴概要指摘

### ISSUE THREAD

**Issue by wararaki718** [ababup1192/curriculum-vitae#1]
> 今後は、関数型・オブジェクト指向問わず優れた技術の先駆者として業界を牽引していきたいと思っている。

個人的な意見ですが、この書き方だと発散しすぎているので、きちんと軸を示して、今後の展開を書いていくとよいかと思います。

４つ箇条書きにした項目から伝えたいことは、学ぶ立場→教える立場→先駆者としてのキャリアを積みたいと伝えると良いかもです。

**Comment by ababup1192** [comment]
ご指摘ありがとうございます。修正致しました。
