### ISSUE TITLE
職務経歴指摘

### ISSUE THREAD

**Issue by wararaki718** [ababup1192/curriculum-vitae#2]
>Scalaクイズアプリ
> Scalaの学習に特化したクイズアプリケーションの開発

アプリと表現すると個人的にダサいと感じるので、クローラーと表現して書いたほうがイイかも。<br>
クローラー開発の経験は需要があるので、目に止まりやすい。

また、収集したデータをどう管理したのか（DBとか入れた？構造データに置き換えた？）など、記載すると、運用面でのアピールができるので良いかともいます。

**Comment by ababup1192** [comment]
ID付け忘れました。
commit 196a3a3049955819dab2b285d7b5ca7de2c10be9 @ababup1192 ababup1192 committed 32 seconds ago

やったことはクローラー開発だけに留まらないので、クイズアプリケーション開発という言葉は残しつつ、別の開発項目を追加し、「スクレイピング」としていたものを「クローリング」と置換しました。
